apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: gitlab-cert
  namespace: gitlab
spec:
  # Secret names are always required.
  secretName: gitlab-cert-tls
  duration: 2160h # 90d
  renewBefore: 360h # 15d
  organization:
  - vmware
  commonName: gitlab.tkg.jb-cloud.com 
  isCA: false
  keySize: 2048
  keyAlgorithm: rsa
  keyEncoding: pkcs1
  # At least one of a DNS Name, USI SAN, or IP address is required.
  dnsNames:
    - gitlab.tkg.jb-cloud.com
    - registry.tkg.jb-cloud.com
    - minio.tkg.jb-cloud.com
  issuerRef:
    name: letsencrypt-contour-cluster-issuer
    # We can reference ClusterIssuers by changing the kind here.
    # The default value is Issuer (i.e. a locally namespaced Issuer)
    kind: ClusterIssuer
